import { Pokemon } from "../interfaces";

const variants: Pokemon[] = [
  {
    originId: 26,
    id: 10100,
    name: "raichu-alola",
    types: ["electric", "psychic"],
    gen: "vii",
    fullEvo: true,
  },
  {
    originId: 103,
    id: 10114,
    name: "exeggutor-alola",
    types: ["grass", "dragon"],
    gen: "vii",
    fullEvo: true,
  },
  {
    originId: 105,
    id: 10115,
    name: "marowak-alola",
    types: ["fire", "ghost"],
    gen: "vii",
    fullEvo: true,
  },
  {
    originId: 658,
    id: 10117,
    name: "greninja-ash",
    types: ["water", "dark"],
    gen: "vii",
    fullEvo: true,
  },
  {
    originId: 718,
    id: 10118,
    name: "zygarde-10-power-construct",
    types: ["dragon", "ground"],
    gen: "vii",
    fullEvo: true,
  },
  {
    originId: 110,
    id: 10167,
    name: "weezing-galar",
    types: ["poison", "fairy"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 157,
    id: 10233,
    name: "typhlosion-hisui",
    types: ["fire", "ghost"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 503,
    id: 10236,
    name: "samurott-hisui",
    types: ["water", "dark"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 724,
    id: 10244,
    name: "decidueye-hisui",
    types: ["grass", "fighting"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 549,
    id: 10237,
    name: "lilligant-hisui",
    types: ["grass", "fighting"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 628,
    id: 10240,
    name: "braviary-hisui",
    types: ["psychic", "flying"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 705,
    id: 10241,
    name: "sliggoo-hisui",
    types: ["steel", "dragon"],
    gen: "viii",
    fullEvo: false,
  },
  {
    originId: 706,
    id: 10242,
    name: "goodra-hisui",
    types: ["steel", "dragon"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 713,
    id: 10243,
    name: "avalugg-hisui",
    types: ["ice", "rock"],
    gen: "viii",
    fullEvo: true,
  },

  {
    originId: 483,
    id: 10245,
    name: "dialga-origin",
    types: ["steel", "dragon"],
    gen: "viii",
    fullEvo: true,
  },
  {
    originId: 485,
    id: 10246,
    name: "palkia-origin",
    types: ["water", "dragon"],
    gen: "viii",
    fullEvo: true,
  },
];

export default variants;
