const megas = [
    {
        originId: 3,
        id: 10033,
        name: "venusaur-mega",
        types: ["grass", "poison"],
        gen: "vi",
    },
    {
        originId: 6,
        id: 10034,
        name: "charizard-mega-x",
        types: ["fire", "dragon"],
        gen: "vi",
    },
    {
        originId: 6,
        id: 10035,
        name: "charizard-mega-y",
        types: ["fire", "flying"],
        gen: "vi",
    },
    {
        originId: 9,
        id: 10036,
        name: "blastoise-mega",
        types: ["water"],
        gen: "vi",
    },
    {
        originId: 65,
        id: 10037,
        name: "alakazam-mega",
        types: ["psychic"],
        gen: "vi",
    },
    {
        originId: 94,
        id: 10038,
        name: "gengar-mega",
        types: ["ghost", "poison"],
        gen: "vi",
    },
    {
        originId: 115,
        id: 10039,
        name: "kangaskhan-mega",
        types: ["normal"],
        gen: "vi",
    },
    {
        originId: 127,
        id: 10040,
        name: "pinsir-mega",
        types: ["bug", "flying"],
        gen: "vi",
    },
    {
        originId: 130,
        id: 10041,
        name: "gyarados-mega",
        types: ["water", "dark"],
        gen: "vi",
    },
    {
        originId: 142,
        id: 10042,
        name: "aerodactyl-mega",
        types: ["rock", "flying"],
        gen: "vi",
    },
    {
        originId: 150,
        id: 10043,
        name: "mewtwo-mega-x",
        types: ["psychic", "fighting"],
        gen: "vi",
    },
    {
        originId: 150,
        id: 10044,
        name: "mewtwo-mega-y",
        types: ["psychic"],
        gen: "vi",
    },
    {
        originId: 181,
        id: 10045,
        name: "ampharos-mega",
        types: ["electric", "dragon"],
        gen: "vi",
    },
    {
        originId: 212,
        id: 10046,
        name: "scizor-mega",
        types: ["bug", "steel"],
        gen: "vi",
    },
    {
        originId: 214,
        id: 10047,
        name: "heracross-mega",
        types: ["bug", "fighting"],
        gen: "vi",
    },
    {
        originId: 229,
        id: 10048,
        name: "houndoom-mega",
        types: ["dark", "fire"],
        gen: "vi",
    },
    {
        originId: 248,
        id: 10049,
        name: "tyranitar-mega",
        types: ["rock", "dark"],
        gen: "vi",
    },
    {
        originId: 257,
        id: 10050,
        name: "blaziken-mega",
        types: ["fire", "fighting"],
        gen: "vi",
    },
    {
        originId: 282,
        id: 10051,
        name: "gardevoir-mega",
        types: ["psychic", "fairy"],
        gen: "vi",
    },
    {
        originId: 303,
        id: 10052,
        name: "mawile-mega",
        types: ["steel", "fairy"],
        gen: "vi",
    },
    {
        originId: 306,
        id: 10053,
        name: "aggron-mega",
        types: ["steel"],
        gen: "vi",
    },
    {
        originId: 308,
        id: 10054,
        name: "medicham-mega",
        types: ["fighting", "psychic"],
        gen: "vi",
    },
    {
        originId: 310,
        id: 10055,
        name: "manectric-mega",
        types: ["electric"],
        gen: "vi",
    },
    {
        originId: 354,
        id: 10056,
        name: "banette-mega",
        types: ["ghost"],
        gen: "vi",
    },
    {
        originId: 359,
        id: 10057,
        name: "absol-mega",
        types: ["dark"],
        gen: "vi",
    },
    {
        originId: 445,
        id: 10058,
        name: "garchomp-mega",
        types: ["dragon", "ground"],
        gen: "vi",
    },
    {
        originId: 448,
        id: 10059,
        name: "lucario-mega",
        types: ["fighting", "steel"],
        gen: "vi",
    },
    {
        originId: 460,
        id: 10060,
        name: "abomasnow-mega",
        types: ["grass", "ice"],
        gen: "vi",
    },
    {
        originId: 380,
        id: 10062,
        name: "latias-mega",
        types: ["dragon", "psychic"],
        gen: "vi",
    },
    {
        originId: 381,
        id: 10063,
        name: "latios-mega",
        types: ["dragon", "psychic"],
        gen: "vi",
    },
    {
        originId: 260,
        id: 10064,
        name: "swampert-mega",
        types: ["water", "ground"],
        gen: "vi",
    },
    {
        originId: 254,
        id: 10065,
        name: "sceptile-mega",
        types: ["grass", "dragon"],
        gen: "vi",
    },
    {
        originId: 302,
        id: 10066,
        name: "sableye-mega",
        types: ["dark", "ghost"],
        gen: "vi",
    },
    {
        originId: 334,
        id: 10067,
        name: "altaria-mega",
        types: ["dragon", "fairy"],
        gen: "vi",
    },
    {
        originId: 475,
        id: 10068,
        name: "gallade-mega",
        types: ["psychic", "fighting"],
        gen: "vi",
    },
    {
        originId: 531,
        id: 10069,
        name: "audino-mega",
        types: ["normal", "fairy"],
        gen: "vi",
    },
    {
        originId: 319,
        id: 10070,
        name: "sharpedo-mega",
        types: ["water", "dark"],
        gen: "vi",
    },
    {
        originId: 80,
        id: 10071,
        name: "slowbro-mega",
        types: ["water", "psychic"],
        gen: "vi",
    },
    {
        originId: 208,
        id: 10072,
        name: "steelix-mega",
        types: ["steel", "ground"],
        gen: "vi",
    },
    {
        originId: 18,
        id: 10073,
        name: "pidgeot-mega",
        types: ["normal", "flying"],
        gen: "vi",
    },
    {
        originId: 362,
        id: 10074,
        name: "glalie-mega",
        types: ["ice"],
        gen: "vi",
    },
    {
        originId: 719,
        id: 10075,
        name: "diancie-mega",
        types: ["rock", "fairy"],
        gen: "vi",
    },
    {
        originId: 376,
        id: 10076,
        name: "metagross-mega",
        types: ["steel", "psychic"],
        gen: "vi",
    },
    {
        originId: 382,
        id: 10077,
        name: "kyogre-primal",
        types: ["water"],
        gen: "vi",
    },
    {
        originId: 383,
        id: 10078,
        name: "groudon-primal",
        types: ["ground", "fire"],
        gen: "vi",
    },
    {
        originId: 384,
        id: 10079,
        name: "rayquaza-mega",
        types: ["dragon", "flying"],
        gen: "vi",
    },
    {
        originId: 323,
        id: 10087,
        name: "camerupt-mega",
        types: ["fire", "ground"],
        gen: "vi",
    },
    {
        originId: 428,
        id: 10088,
        name: "lopunny-mega",
        types: ["normal", "fighting"],
        gen: "vi",
    },
    {
        originId: 373,
        id: 10089,
        name: "salamence-mega",
        types: ["dragon", "flying"],
        gen: "vi",
    },
    {
        originId: 15,
        id: 10090,
        name: "beedrill-mega",
        types: ["bug", "poison"],
        gen: "vi",
    },
];
export default megas;
